// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"

	"github.com/oapi-codegen/nullable"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ACULimitResponseScope.
const (
	ACULimitResponseScopeEnterprise ACULimitResponseScope = "enterprise"
	ACULimitResponseScopeOrg        ACULimitResponseScope = "org"
	ACULimitResponseScopeUser       ACULimitResponseScope = "user"
)

// Defines values for GitConnectionResponseGitProviderType.
const (
	AzureDevopsOauth      GitConnectionResponseGitProviderType = "azure_devops_oauth"
	BitbucketOauth        GitConnectionResponseGitProviderType = "bitbucket_oauth"
	BitbucketToken        GitConnectionResponseGitProviderType = "bitbucket_token"
	GithubApp             GitConnectionResponseGitProviderType = "github_app"
	GithubIndividualToken GitConnectionResponseGitProviderType = "github_individual_token"
	GithubToken           GitConnectionResponseGitProviderType = "github_token"
	GitlabOauth           GitConnectionResponseGitProviderType = "gitlab_oauth"
	GitlabToken           GitConnectionResponseGitProviderType = "gitlab_token"
)

// Defines values for KnowledgeNoteResponseAccessType.
const (
	KnowledgeNoteResponseAccessTypeEnterprise KnowledgeNoteResponseAccessType = "enterprise"
	KnowledgeNoteResponseAccessTypeOrg        KnowledgeNoteResponseAccessType = "org"
)

// Defines values for PlaybookResponseAccessType.
const (
	PlaybookResponseAccessTypeEnterprise PlaybookResponseAccessType = "enterprise"
	PlaybookResponseAccessTypeOrg        PlaybookResponseAccessType = "org"
)

// Defines values for RoleRoleType.
const (
	RoleRoleTypeEnterprise RoleRoleType = "enterprise"
	RoleRoleTypeOrg        RoleRoleType = "org"
)

// Defines values for ScheduleCreateRequestAgent.
const (
	ScheduleCreateRequestAgentDataAnalyst ScheduleCreateRequestAgent = "data_analyst"
	ScheduleCreateRequestAgentDevin       ScheduleCreateRequestAgent = "devin"
)

// Defines values for ScheduleCreateRequestNotifyOn.
const (
	ScheduleCreateRequestNotifyOnAlways  ScheduleCreateRequestNotifyOn = "always"
	ScheduleCreateRequestNotifyOnFailure ScheduleCreateRequestNotifyOn = "failure"
	ScheduleCreateRequestNotifyOnNever   ScheduleCreateRequestNotifyOn = "never"
)

// Defines values for ScheduleCreateRequestScheduleType.
const (
	ScheduleCreateRequestScheduleTypeOneTime   ScheduleCreateRequestScheduleType = "one_time"
	ScheduleCreateRequestScheduleTypeRecurring ScheduleCreateRequestScheduleType = "recurring"
)

// Defines values for ScheduleResponseAgent.
const (
	ScheduleResponseAgentDataAnalyst ScheduleResponseAgent = "data_analyst"
	ScheduleResponseAgentDevin       ScheduleResponseAgent = "devin"
)

// Defines values for ScheduleResponseNotifyOn.
const (
	ScheduleResponseNotifyOnAlways  ScheduleResponseNotifyOn = "always"
	ScheduleResponseNotifyOnFailure ScheduleResponseNotifyOn = "failure"
	ScheduleResponseNotifyOnNever   ScheduleResponseNotifyOn = "never"
)

// Defines values for ScheduleResponseScheduleType.
const (
	ScheduleResponseScheduleTypeOneTime   ScheduleResponseScheduleType = "one_time"
	ScheduleResponseScheduleTypeRecurring ScheduleResponseScheduleType = "recurring"
)

// Defines values for ScheduleUpdateRequestAgent.
const (
	DataAnalyst ScheduleUpdateRequestAgent = "data_analyst"
	Devin       ScheduleUpdateRequestAgent = "devin"
)

// Defines values for ScheduleUpdateRequestNotifyOn.
const (
	Always  ScheduleUpdateRequestNotifyOn = "always"
	Failure ScheduleUpdateRequestNotifyOn = "failure"
	Never   ScheduleUpdateRequestNotifyOn = "never"
)

// Defines values for ScheduleUpdateRequestScheduleType.
const (
	OneTime   ScheduleUpdateRequestScheduleType = "one_time"
	Recurring ScheduleUpdateRequestScheduleType = "recurring"
)

// Defines values for SecretCreateRequestType.
const (
	SecretCreateRequestTypeCookie   SecretCreateRequestType = "cookie"
	SecretCreateRequestTypeKeyValue SecretCreateRequestType = "key-value"
	SecretCreateRequestTypeTotp     SecretCreateRequestType = "totp"
)

// Defines values for SecretResponseAccessType.
const (
	SecretResponseAccessTypeOrg      SecretResponseAccessType = "org"
	SecretResponseAccessTypePersonal SecretResponseAccessType = "personal"
)

// Defines values for SecretResponseSecretType.
const (
	SecretResponseSecretTypeCookie   SecretResponseSecretType = "cookie"
	SecretResponseSecretTypeKeyValue SecretResponseSecretType = "key-value"
	SecretResponseSecretTypeTotp     SecretResponseSecretType = "totp"
)

// Defines values for HandleListNotesV3EnterpriseKnowledgeNotesGetParamsAccessType.
const (
	HandleListNotesV3EnterpriseKnowledgeNotesGetParamsAccessTypeEnterprise HandleListNotesV3EnterpriseKnowledgeNotesGetParamsAccessType = "enterprise"
	HandleListNotesV3EnterpriseKnowledgeNotesGetParamsAccessTypeOrg        HandleListNotesV3EnterpriseKnowledgeNotesGetParamsAccessType = "org"
)

// ACULimitResponse defines model for ACULimitResponse.
type ACULimitResponse struct {
	CycleAcuLimit int                       `json:"cycle_acu_limit"`
	OrgID         nullable.Nullable[string] `json:"org_id,omitempty"`
	Scope         ACULimitResponseScope     `json:"scope"`
	UserID        nullable.Nullable[string] `json:"user_id,omitempty"`
}

// ACULimitResponseScope defines model for ACULimitResponse.Scope.
type ACULimitResponseScope string

// DefaultTagRequest defines model for DefaultTagRequest.
type DefaultTagRequest struct {
	Tag string `json:"tag"`
}

// DefaultTagResponse defines model for DefaultTagResponse.
type DefaultTagResponse struct {
	DefaultTag nullable.Nullable[string] `json:"default_tag"`
}

// FolderSummary One folder in the knowledge folder tree.
type FolderSummary struct {
	FolderID       string                    `json:"folder_id"`
	Name           string                    `json:"name"`
	NoteCount      int                       `json:"note_count"`
	ParentFolderID nullable.Nullable[string] `json:"parent_folder_id,omitempty"`
	Path           string                    `json:"path"`
}

// FolderTreeResponse Response for the folder-structure endpoint.
type FolderTreeResponse struct {
	Folders       []FolderSummary `json:"folders"`
	RootNoteCount int             `json:"root_note_count"`
}

// GitConnectionRepositoryResponse defines model for GitConnectionRepositoryResponse.
type GitConnectionRepositoryResponse struct {
	GitConnectionHost    string                    `json:"git_connection_host"`
	GitConnectionID      string                    `json:"git_connection_id"`
	LastUpdatedAt        nullable.Nullable[int]    `json:"last_updated_at"`
	ProviderRepositoryID string                    `json:"provider_repository_id"`
	RepoDescription      nullable.Nullable[string] `json:"repo_description"`
	RepoLanguage         nullable.Nullable[string] `json:"repo_language"`
	RepoName             string                    `json:"repo_name"`
	RepoPath             string                    `json:"repo_path"`
}

// GitConnectionResponse defines model for GitConnectionResponse.
type GitConnectionResponse struct {
	CreatedAt       int                                  `json:"created_at"`
	GitConnectionID string                               `json:"git_connection_id"`
	GitProviderType GitConnectionResponseGitProviderType `json:"git_provider_type"`
	Host            string                               `json:"host"`
	Name            nullable.Nullable[string]            `json:"name"`
}

// GitConnectionResponseGitProviderType defines model for GitConnectionResponse.GitProviderType.
type GitConnectionResponseGitProviderType string

// GitPermissionBulkCreateRequest defines model for GitPermissionBulkCreateRequest.
type GitPermissionBulkCreateRequest struct {
	Permissions []GitPermissionCreateRequest `json:"permissions"`
}

// GitPermissionCreateRequest defines model for GitPermissionCreateRequest.
type GitPermissionCreateRequest struct {
	GitConnectionID string                    `json:"git_connection_id"`
	GroupPrefix     nullable.Nullable[string] `json:"group_prefix,omitempty"`
	PrefixPath      nullable.Nullable[string] `json:"prefix_path,omitempty"`
	ReadOnly        *bool                     `json:"read_only,omitempty"`
	RepoPath        nullable.Nullable[string] `json:"repo_path,omitempty"`
}

// GitPermissionResponse defines model for GitPermissionResponse.
type GitPermissionResponse struct {
	CreatedAt       nullable.Nullable[int]    `json:"created_at,omitempty"`
	GitConnectionID string                    `json:"git_connection_id"`
	GitPermissionID string                    `json:"git_permission_id"`
	GroupPrefix     nullable.Nullable[string] `json:"group_prefix,omitempty"`
	PrefixPath      nullable.Nullable[string] `json:"prefix_path,omitempty"`
	ReadOnly        *bool                     `json:"read_only,omitempty"`
	RepoPath        nullable.Nullable[string] `json:"repo_path,omitempty"`
}

// GitPermissionUpdateRequest defines model for GitPermissionUpdateRequest.
type GitPermissionUpdateRequest struct {
	ReadOnly nullable.Nullable[bool] `json:"read_only,omitempty"`
}

// IdpGroup defines model for IdpGroup.
type IdpGroup struct {
	IdpGroupName    string           `json:"idp_group_name"`
	RoleAssignments []RoleAssignment `json:"role_assignments"`
}

// IdpGroupResponse defines model for IdpGroupResponse.
type IdpGroupResponse struct {
	IdpGroupName string `json:"idp_group_name"`
}

// IdpGroupUpdateRoleRequest defines model for IdpGroupUpdateRoleRequest.
type IdpGroupUpdateRoleRequest struct {
	RoleID string `json:"role_id"`
}

// IdpGroupUser A user whose membership is derived from IDP group assignments.
type IdpGroupUser struct {
	Email              nullable.Nullable[string] `json:"email"`
	IdpRoleAssignments []IdpRoleAssignment       `json:"idp_role_assignments"`
	Name               nullable.Nullable[string] `json:"name"`
	UserID             string                    `json:"user_id"`
}

// IdpGroupsBulkCreateRequest defines model for IdpGroupsBulkCreateRequest.
type IdpGroupsBulkCreateRequest struct {
	IdpGroupNames []string `json:"idp_group_names"`
}

// IdpRoleAssignment A role assignment inherited via IDP group membership.
type IdpRoleAssignment struct {
	IdpGroupName string                    `json:"idp_group_name"`
	OrgID        nullable.Nullable[string] `json:"org_id,omitempty"`
	Role         Role                      `json:"role"`
}

// IPAccessListAddRequest defines model for IpAccessListAddRequest.
type IPAccessListAddRequest struct {
	IPRanges []string `json:"ip_ranges"`
}

// IPAccessListReplaceRequest defines model for IpAccessListReplaceRequest.
type IPAccessListReplaceRequest struct {
	IPRanges []string `json:"ip_ranges"`
}

// IPAccessListResponse defines model for IpAccessListResponse.
type IPAccessListResponse struct {
	IPRanges []string `json:"ip_ranges"`
}

// KnowledgeNoteCreateRequest defines model for KnowledgeNoteCreateRequest.
type KnowledgeNoteCreateRequest struct {
	Body       string                    `json:"body"`
	FolderID   nullable.Nullable[string] `json:"folder_id,omitempty"`
	IsEnabled  nullable.Nullable[bool]   `json:"is_enabled,omitempty"`
	Name       string                    `json:"name"`
	PinnedRepo nullable.Nullable[string] `json:"pinned_repo,omitempty"`
	Trigger    string                    `json:"trigger"`
}

// KnowledgeNoteResponse defines model for KnowledgeNoteResponse.
type KnowledgeNoteResponse struct {
	AccessType KnowledgeNoteResponseAccessType `json:"access_type"`
	Body       string                          `json:"body"`
	CreatedAt  int                             `json:"created_at"`
	FolderID   nullable.Nullable[string]       `json:"folder_id"`
	FolderPath string                          `json:"folder_path"`
	IsEnabled  bool                            `json:"is_enabled"`
	Macro      nullable.Nullable[string]       `json:"macro"`
	Name       string                          `json:"name"`
	NoteID     string                          `json:"note_id"`
	OrgID      nullable.Nullable[string]       `json:"org_id"`
	PinnedRepo nullable.Nullable[string]       `json:"pinned_repo"`
	Trigger    string                          `json:"trigger"`
	UpdatedAt  int                             `json:"updated_at"`
}

// KnowledgeNoteResponseAccessType defines model for KnowledgeNoteResponse.AccessType.
type KnowledgeNoteResponseAccessType string

// OrgGroupConfig defines model for OrgGroupConfig.
type OrgGroupConfig struct {
	MaxCycleAcus nullable.Nullable[int] `json:"max_cycle_acus,omitempty"`
	OrgIds       []string               `json:"org_ids"`
}

// OrgGroupsConfig Configuration mapping group names to their settings.
type OrgGroupsConfig struct {
	Groups map[string]OrgGroupConfig `json:"groups"`
}

// OrganizationCreateRequest defines model for OrganizationCreateRequest.
type OrganizationCreateRequest struct {
	MaxCycleAcuLimit   nullable.Nullable[int] `json:"max_cycle_acu_limit,omitempty"`
	MaxSessionAcuLimit nullable.Nullable[int] `json:"max_session_acu_limit,omitempty"`
	Name               string                 `json:"name"`
}

// OrganizationResponse defines model for OrganizationResponse.
type OrganizationResponse struct {
	CreatedAt          int                    `json:"created_at"`
	MaxCycleAcuLimit   nullable.Nullable[int] `json:"max_cycle_acu_limit"`
	MaxSessionAcuLimit nullable.Nullable[int] `json:"max_session_acu_limit"`
	Name               string                 `json:"name"`
	OrgID              string                 `json:"org_id"`
	UpdatedAt          int                    `json:"updated_at"`
}

// OrganizationUpdateRequest defines model for OrganizationUpdateRequest.
type OrganizationUpdateRequest struct {
	MaxCycleAcuLimit   nullable.Nullable[int]    `json:"max_cycle_acu_limit,omitempty"`
	MaxSessionAcuLimit nullable.Nullable[int]    `json:"max_session_acu_limit,omitempty"`
	Name               nullable.Nullable[string] `json:"name,omitempty"`
}

// PaginatedResponseACULimitResponse defines model for PaginatedResponse_ACULimitResponse_.
type PaginatedResponseACULimitResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool              `json:"has_next_page,omitempty"`
	Items       []ACULimitResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseGitConnectionRepositoryResponse defines model for PaginatedResponse_GitConnectionRepositoryResponse_.
type PaginatedResponseGitConnectionRepositoryResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool                             `json:"has_next_page,omitempty"`
	Items       []GitConnectionRepositoryResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseGitConnectionResponse defines model for PaginatedResponse_GitConnectionResponse_.
type PaginatedResponseGitConnectionResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool                   `json:"has_next_page,omitempty"`
	Items       []GitConnectionResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseGitPermissionResponse defines model for PaginatedResponse_GitPermissionResponse_.
type PaginatedResponseGitPermissionResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool                   `json:"has_next_page,omitempty"`
	Items       []GitPermissionResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseIdpGroupResponse defines model for PaginatedResponse_IdpGroupResponse_.
type PaginatedResponseIdpGroupResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool              `json:"has_next_page,omitempty"`
	Items       []IdpGroupResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseIdpGroupUser defines model for PaginatedResponse_IdpGroupUser_.
type PaginatedResponseIdpGroupUser struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool          `json:"has_next_page,omitempty"`
	Items       []IdpGroupUser `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseIdpGroup defines model for PaginatedResponse_IdpGroup_.
type PaginatedResponseIdpGroup struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool      `json:"has_next_page,omitempty"`
	Items       []IdpGroup `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseKnowledgeNoteResponse defines model for PaginatedResponse_KnowledgeNoteResponse_.
type PaginatedResponseKnowledgeNoteResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool                   `json:"has_next_page,omitempty"`
	Items       []KnowledgeNoteResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseOrganizationResponse defines model for PaginatedResponse_OrganizationResponse_.
type PaginatedResponseOrganizationResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool                  `json:"has_next_page,omitempty"`
	Items       []OrganizationResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponsePlaybookResponse defines model for PaginatedResponse_PlaybookResponse_.
type PaginatedResponsePlaybookResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool              `json:"has_next_page,omitempty"`
	Items       []PlaybookResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseRole defines model for PaginatedResponse_Role_.
type PaginatedResponseRole struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool  `json:"has_next_page,omitempty"`
	Items       []Role `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseScheduleResponse defines model for PaginatedResponse_ScheduleResponse_.
type PaginatedResponseScheduleResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool              `json:"has_next_page,omitempty"`
	Items       []ScheduleResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseSecretResponse defines model for PaginatedResponse_SecretResponse_.
type PaginatedResponseSecretResponse struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool            `json:"has_next_page,omitempty"`
	Items       []SecretResponse `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseServiceUser defines model for PaginatedResponse_ServiceUser_.
type PaginatedResponseServiceUser struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool         `json:"has_next_page,omitempty"`
	Items       []ServiceUser `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PaginatedResponseUser defines model for PaginatedResponse_User_.
type PaginatedResponseUser struct {
	// EndCursor Cursor to fetch the next page, or None if this is the last page.
	EndCursor nullable.Nullable[string] `json:"end_cursor,omitempty"`

	// HasNextPage Whether there are more items available after this page.
	HasNextPage *bool  `json:"has_next_page,omitempty"`
	Items       []User `json:"items"`

	// Total Optional total count (can be omitted for performance).
	Total nullable.Nullable[int] `json:"total,omitempty"`
}

// PlaybookCreateRequest defines model for PlaybookCreateRequest.
type PlaybookCreateRequest struct {
	Body string `json:"body"`

	// Macro Playbook macro identifier. Must start with '!' followed by one or more letters, digits, underscores, or hyphens. Example: '!my_macro' or '!my-macro'
	Macro nullable.Nullable[string] `json:"macro,omitempty"`

	// StructuredOutputSchema JSON Schema (Draft 7) that sessions using this playbook will produce as structured output. Max 64KB. Must be self-contained (no external $ref).
	StructuredOutputSchema nullable.Nullable[map[string]interface{}] `json:"structured_output_schema,omitempty"`
	Title                  string                                    `json:"title"`
}

// PlaybookInfo defines model for PlaybookInfo.
type PlaybookInfo struct {
	PlaybookID string                    `json:"playbook_id"`
	Title      nullable.Nullable[string] `json:"title"`
}

// PlaybookResponse defines model for PlaybookResponse.
type PlaybookResponse struct {
	AccessType             PlaybookResponseAccessType                `json:"access_type"`
	Body                   string                                    `json:"body"`
	CreatedAt              int                                       `json:"created_at"`
	CreatedBy              string                                    `json:"created_by"`
	Macro                  nullable.Nullable[string]                 `json:"macro"`
	OrgID                  nullable.Nullable[string]                 `json:"org_id"`
	PlaybookID             string                                    `json:"playbook_id"`
	StructuredOutputSchema nullable.Nullable[map[string]interface{}] `json:"structured_output_schema,omitempty"`
	Title                  string                                    `json:"title"`
	UpdatedAt              int                                       `json:"updated_at"`
	UpdatedBy              string                                    `json:"updated_by"`
}

// PlaybookResponseAccessType defines model for PlaybookResponse.AccessType.
type PlaybookResponseAccessType string

// Role defines model for Role.
type Role struct {
	RoleID   string       `json:"role_id"`
	RoleName string       `json:"role_name"`
	RoleType RoleRoleType `json:"role_type"`
}

// RoleRoleType defines model for Role.RoleType.
type RoleRoleType string

// RoleAssignment defines model for RoleAssignment.
type RoleAssignment struct {
	OrgID nullable.Nullable[string] `json:"org_id,omitempty"`
	Role  Role                      `json:"role"`
}

// ScheduleCreateRequest defines model for ScheduleCreateRequest.
type ScheduleCreateRequest struct {
	Agent          *ScheduleCreateRequestAgent    `json:"agent,omitempty"`
	BypassApproval *bool                          `json:"bypass_approval,omitempty"`
	CreateAsUserID nullable.Nullable[string]      `json:"create_as_user_id,omitempty"`
	Frequency      nullable.Nullable[string]      `json:"frequency,omitempty"`
	IntervalCount  *int                           `json:"interval_count,omitempty"`
	Name           string                         `json:"name"`
	NotifyOn       *ScheduleCreateRequestNotifyOn `json:"notify_on,omitempty"`

	// Platform VM platform for sessions spawned by this schedule (e.g. 'windows'). When omitted, sessions fall back to the org's default platform at trigger time. Value must match a platform configured for the organization (case-insensitive); unknown values are rejected with a 400 that lists the available platform labels.
	Platform       nullable.Nullable[string]          `json:"platform,omitempty"`
	PlaybookID     nullable.Nullable[string]          `json:"playbook_id,omitempty"`
	Prompt         string                             `json:"prompt"`
	ScheduleType   *ScheduleCreateRequestScheduleType `json:"schedule_type,omitempty"`
	ScheduledAt    nullable.Nullable[time.Time]       `json:"scheduled_at,omitempty"`
	SlackChannelID nullable.Nullable[string]          `json:"slack_channel_id,omitempty"`
	SlackTeamID    nullable.Nullable[string]          `json:"slack_team_id,omitempty"`
	Tags           nullable.Nullable[[]string]        `json:"tags,omitempty"`
	TargetDevinID  nullable.Nullable[string]          `json:"target_devin_id,omitempty"`
}

// ScheduleCreateRequestAgent defines model for ScheduleCreateRequest.Agent.
type ScheduleCreateRequestAgent string

// ScheduleCreateRequestNotifyOn defines model for ScheduleCreateRequest.NotifyOn.
type ScheduleCreateRequestNotifyOn string

// ScheduleCreateRequestScheduleType defines model for ScheduleCreateRequest.ScheduleType.
type ScheduleCreateRequestScheduleType string

// ScheduleResponse defines model for ScheduleResponse.
type ScheduleResponse struct {
	Agent               ScheduleResponseAgent           `json:"agent"`
	BypassApproval      *bool                           `json:"bypass_approval,omitempty"`
	ConsecutiveFailures int                             `json:"consecutive_failures"`
	CreatedAt           time.Time                       `json:"created_at"`
	CreatedBy           nullable.Nullable[string]       `json:"created_by"`
	Enabled             bool                            `json:"enabled"`
	Frequency           nullable.Nullable[string]       `json:"frequency"`
	IntervalCount       *int                            `json:"interval_count,omitempty"`
	LastEditedBy        nullable.Nullable[string]       `json:"last_edited_by,omitempty"`
	LastErrorAt         nullable.Nullable[time.Time]    `json:"last_error_at"`
	LastErrorMessage    nullable.Nullable[string]       `json:"last_error_message"`
	LastExecutedAt      nullable.Nullable[time.Time]    `json:"last_executed_at"`
	Name                string                          `json:"name"`
	NotifyOn            ScheduleResponseNotifyOn        `json:"notify_on"`
	OrgID               string                          `json:"org_id"`
	Platform            nullable.Nullable[string]       `json:"platform,omitempty"`
	Playbook            nullable.Nullable[PlaybookInfo] `json:"playbook"`
	Prompt              string                          `json:"prompt"`
	ScheduleType        *ScheduleResponseScheduleType   `json:"schedule_type,omitempty"`
	ScheduledAt         nullable.Nullable[time.Time]    `json:"scheduled_at,omitempty"`
	ScheduledSessionID  string                          `json:"scheduled_session_id"`
	SlackChannelID      nullable.Nullable[string]       `json:"slack_channel_id,omitempty"`
	SlackTeamID         nullable.Nullable[string]       `json:"slack_team_id,omitempty"`
	Tags                nullable.Nullable[[]string]     `json:"tags,omitempty"`
	TargetDevinID       nullable.Nullable[string]       `json:"target_devin_id,omitempty"`
	UpdatedAt           time.Time                       `json:"updated_at"`
}

// ScheduleResponseAgent defines model for ScheduleResponse.Agent.
type ScheduleResponseAgent string

// ScheduleResponseNotifyOn defines model for ScheduleResponse.NotifyOn.
type ScheduleResponseNotifyOn string

// ScheduleResponseScheduleType defines model for ScheduleResponse.ScheduleType.
type ScheduleResponseScheduleType string

// ScheduleUpdateRequest defines model for ScheduleUpdateRequest.
type ScheduleUpdateRequest struct {
	Agent          nullable.Nullable[ScheduleUpdateRequestAgent]    `json:"agent,omitempty"`
	BypassApproval nullable.Nullable[bool]                          `json:"bypass_approval,omitempty"`
	Enabled        nullable.Nullable[bool]                          `json:"enabled,omitempty"`
	Frequency      nullable.Nullable[string]                        `json:"frequency,omitempty"`
	IntervalCount  nullable.Nullable[int]                           `json:"interval_count,omitempty"`
	Name           nullable.Nullable[string]                        `json:"name,omitempty"`
	NotifyOn       nullable.Nullable[ScheduleUpdateRequestNotifyOn] `json:"notify_on,omitempty"`

	// Platform VM platform for sessions spawned by this schedule (e.g. 'windows'). When omitted, the platform is left unchanged. Value must match a platform configured for the organization (case-insensitive); unknown values are rejected with a 400 that lists the available platform labels.
	Platform   nullable.Nullable[string] `json:"platform,omitempty"`
	PlaybookID nullable.Nullable[string] `json:"playbook_id,omitempty"`
	Prompt     nullable.Nullable[string] `json:"prompt,omitempty"`

	// RunAsUserID Set the user ID that this schedule will run as. Requires ImpersonateOrgSessions permission. Setting to null reverts to the default bot user. Omitting the field leaves the current identity unchanged.
	RunAsUserID    nullable.Nullable[string]                            `json:"run_as_user_id,omitempty"`
	ScheduleType   nullable.Nullable[ScheduleUpdateRequestScheduleType] `json:"schedule_type,omitempty"`
	ScheduledAt    nullable.Nullable[time.Time]                         `json:"scheduled_at,omitempty"`
	SlackChannelID nullable.Nullable[string]                            `json:"slack_channel_id,omitempty"`
	SlackTeamID    nullable.Nullable[string]                            `json:"slack_team_id,omitempty"`
	Tags           nullable.Nullable[[]string]                          `json:"tags,omitempty"`
	TargetDevinID  nullable.Nullable[string]                            `json:"target_devin_id,omitempty"`
}

// ScheduleUpdateRequestAgent defines model for ScheduleUpdateRequest.Agent.
type ScheduleUpdateRequestAgent string

// ScheduleUpdateRequestNotifyOn defines model for ScheduleUpdateRequest.NotifyOn.
type ScheduleUpdateRequestNotifyOn string

// ScheduleUpdateRequestScheduleType defines model for ScheduleUpdateRequest.ScheduleType.
type ScheduleUpdateRequestScheduleType string

// SecretCreateRequest defines model for SecretCreateRequest.
type SecretCreateRequest struct {
	IsSensitive *bool                     `json:"is_sensitive,omitempty"`
	Key         string                    `json:"key"`
	Note        nullable.Nullable[string] `json:"note,omitempty"`
	Type        SecretCreateRequestType   `json:"type"`
	Value       string                    `json:"value"`
}

// SecretCreateRequestType defines model for SecretCreateRequest.Type.
type SecretCreateRequestType string

// SecretResponse defines model for SecretResponse.
type SecretResponse struct {
	AccessType  SecretResponseAccessType  `json:"access_type"`
	CreatedAt   int                       `json:"created_at"`
	CreatedBy   string                    `json:"created_by"`
	IsSensitive bool                      `json:"is_sensitive"`
	Key         nullable.Nullable[string] `json:"key"`
	Note        nullable.Nullable[string] `json:"note"`
	SecretID    string                    `json:"secret_id"`
	SecretType  SecretResponseSecretType  `json:"secret_type"`
	UpdatedAt   nullable.Nullable[int]    `json:"updated_at,omitempty"`
	UpdatedBy   nullable.Nullable[string] `json:"updated_by,omitempty"`
}

// SecretResponseAccessType defines model for SecretResponse.AccessType.
type SecretResponseAccessType string

// SecretResponseSecretType defines model for SecretResponse.SecretType.
type SecretResponseSecretType string

// ServiceUser defines model for ServiceUser.
type ServiceUser struct {
	DeletedAt       nullable.Nullable[int] `json:"deleted_at"`
	ExpiresAt       nullable.Nullable[int] `json:"expires_at"`
	Name            string                 `json:"name"`
	RoleAssignments []RoleAssignment       `json:"role_assignments"`
	ServiceUserID   string                 `json:"service_user_id"`
}

// ServiceUserUpdateRoleRequest defines model for ServiceUserUpdateRoleRequest.
type ServiceUserUpdateRoleRequest struct {
	RoleID string `json:"role_id"`
}

// TagsCreateRequest defines model for TagsCreateRequest.
type TagsCreateRequest struct {
	Tags []string `json:"tags"`
}

// TagsResponse defines model for TagsResponse.
type TagsResponse struct {
	Tags []string `json:"tags"`
}

// UpdateACULimitRequest defines model for UpdateACULimitRequest.
type UpdateACULimitRequest struct {
	CycleAcuLimit int `json:"cycle_acu_limit"`
}

// User defines model for User.
type User struct {
	Email           nullable.Nullable[string] `json:"email"`
	Name            nullable.Nullable[string] `json:"name"`
	RoleAssignments []RoleAssignment          `json:"role_assignments"`
	UserID          string                    `json:"user_id"`
}

// UserBulkCreateRequest defines model for UserBulkCreateRequest.
type UserBulkCreateRequest struct {
	Emails           []string `json:"emails"`
	EnterpriseRoleID string   `json:"enterprise_role_id"`
}

// UserUpdateRoleRequest defines model for UserUpdateRoleRequest.
type UserUpdateRoleRequest struct {
	RoleID string `json:"role_id"`
}

// UserWithIdpRoles User with both direct and IDP-group-derived role assignments.
type UserWithIdpRoles struct {
	Email              nullable.Nullable[string] `json:"email"`
	IdpRoleAssignments *[]IdpRoleAssignment      `json:"idp_role_assignments,omitempty"`
	Name               nullable.Nullable[string] `json:"name"`
	RoleAssignments    []RoleAssignment          `json:"role_assignments"`
	UserID             string                    `json:"user_id"`
}

// HandleGetDevinAcuLimitsV3EnterpriseConsumptionAcuLimitsDevinGetParams defines parameters for HandleGetDevinAcuLimitsV3EnterpriseConsumptionAcuLimitsDevinGet.
type HandleGetDevinAcuLimitsV3EnterpriseConsumptionAcuLimitsDevinGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleGetGitConnectionsV3EnterpriseGitProvidersConnectionsGetParams defines parameters for HandleGetGitConnectionsV3EnterpriseGitProvidersConnectionsGet.
type HandleGetGitConnectionsV3EnterpriseGitProvidersConnectionsGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleListGitConnectionRepositoriesV3EnterpriseGitProvidersConnectionsConnectionIDRepositoriesGetParams defines parameters for HandleListGitConnectionRepositoriesV3EnterpriseGitProvidersConnectionsConnectionIDRepositoriesGet.
type HandleListGitConnectionRepositoriesV3EnterpriseGitProvidersConnectionsConnectionIDRepositoriesGetParams struct {
	After      *string `form:"after,omitempty" json:"after,omitempty"`
	First      *int    `form:"first,omitempty" json:"first,omitempty"`
	FilterName *string `form:"filter_name,omitempty" json:"filter_name,omitempty"`
}

// HandleListAccountIdpGroupsV3EnterpriseIdpGroupsGetParams defines parameters for HandleListAccountIdpGroupsV3EnterpriseIdpGroupsGet.
type HandleListAccountIdpGroupsV3EnterpriseIdpGroupsGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleListNotesV3EnterpriseKnowledgeNotesGetParams defines parameters for HandleListNotesV3EnterpriseKnowledgeNotesGet.
type HandleListNotesV3EnterpriseKnowledgeNotesGetParams struct {
	After      *string                                                       `form:"after,omitempty" json:"after,omitempty"`
	First      *int                                                          `form:"first,omitempty" json:"first,omitempty"`
	AccessType *HandleListNotesV3EnterpriseKnowledgeNotesGetParamsAccessType `form:"access_type,omitempty" json:"access_type,omitempty"`
	Search     *string                                                       `form:"search,omitempty" json:"search,omitempty"`
	FolderPath *string                                                       `form:"folder_path,omitempty" json:"folder_path,omitempty"`
	PinnedRepo *string                                                       `form:"pinned_repo,omitempty" json:"pinned_repo,omitempty"`
}

// HandleListNotesV3EnterpriseKnowledgeNotesGetParamsAccessType defines parameters for HandleListNotesV3EnterpriseKnowledgeNotesGet.
type HandleListNotesV3EnterpriseKnowledgeNotesGetParamsAccessType string

// HandleListEnterpriseIdpGroupsV3EnterpriseMembersIdpGroupsGetParams defines parameters for HandleListEnterpriseIdpGroupsV3EnterpriseMembersIdpGroupsGet.
type HandleListEnterpriseIdpGroupsV3EnterpriseMembersIdpGroupsGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleListEnterpriseIdpUsersV3EnterpriseMembersIdpUsersGetParams defines parameters for HandleListEnterpriseIdpUsersV3EnterpriseMembersIdpUsersGet.
type HandleListEnterpriseIdpUsersV3EnterpriseMembersIdpUsersGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`

	// Email Filter by exact email address
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}

// HandleListEnterpriseServiceUsersV3EnterpriseMembersServiceUsersGetParams defines parameters for HandleListEnterpriseServiceUsersV3EnterpriseMembersServiceUsersGet.
type HandleListEnterpriseServiceUsersV3EnterpriseMembersServiceUsersGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`

	// IncludeInactive Include inactive service users (expired or removed).
	IncludeInactive *bool `form:"include_inactive,omitempty" json:"include_inactive,omitempty"`
}

// HandleListEnterpriseUsersV3EnterpriseMembersUsersGetParams defines parameters for HandleListEnterpriseUsersV3EnterpriseMembersUsersGet.
type HandleListEnterpriseUsersV3EnterpriseMembersUsersGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`

	// Email Filter by exact email address
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}

// HandleGetOrganizationsV3EnterpriseOrganizationsGetParams defines parameters for HandleGetOrganizationsV3EnterpriseOrganizationsGet.
type HandleGetOrganizationsV3EnterpriseOrganizationsGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleGetOrganizationGitPermissionsV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsGetParams defines parameters for HandleGetOrganizationGitPermissionsV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsGet.
type HandleGetOrganizationGitPermissionsV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleListOrganizationIdpGroupsV3EnterpriseOrganizationsOrgIDMembersIdpGroupsGetParams defines parameters for HandleListOrganizationIdpGroupsV3EnterpriseOrganizationsOrgIDMembersIdpGroupsGet.
type HandleListOrganizationIdpGroupsV3EnterpriseOrganizationsOrgIDMembersIdpGroupsGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleListOrganizationIdpUsersV3EnterpriseOrganizationsOrgIDMembersIdpUsersGetParams defines parameters for HandleListOrganizationIdpUsersV3EnterpriseOrganizationsOrgIDMembersIdpUsersGet.
type HandleListOrganizationIdpUsersV3EnterpriseOrganizationsOrgIDMembersIdpUsersGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`

	// Email Filter by exact email address
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}

// HandleListOrganizationServiceUsersV3EnterpriseOrganizationsOrgIDMembersServiceUsersGetParams defines parameters for HandleListOrganizationServiceUsersV3EnterpriseOrganizationsOrgIDMembersServiceUsersGet.
type HandleListOrganizationServiceUsersV3EnterpriseOrganizationsOrgIDMembersServiceUsersGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`

	// IncludeInactive Include inactive service users (expired or removed).
	IncludeInactive *bool `form:"include_inactive,omitempty" json:"include_inactive,omitempty"`
}

// HandleListOrganizationUsersV3EnterpriseOrganizationsOrgIDMembersUsersGetParams defines parameters for HandleListOrganizationUsersV3EnterpriseOrganizationsOrgIDMembersUsersGet.
type HandleListOrganizationUsersV3EnterpriseOrganizationsOrgIDMembersUsersGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`

	// Email Filter by exact email address
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}

// HandleListPlaybooksV3EnterprisePlaybooksGetParams defines parameters for HandleListPlaybooksV3EnterprisePlaybooksGet.
type HandleListPlaybooksV3EnterprisePlaybooksGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleGetRolesV3EnterpriseRolesGetParams defines parameters for HandleGetRolesV3EnterpriseRolesGet.
type HandleGetRolesV3EnterpriseRolesGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleListNotesV3OrganizationsOrgIDKnowledgeNotesGetParams defines parameters for HandleListNotesV3OrganizationsOrgIDKnowledgeNotesGet.
type HandleListNotesV3OrganizationsOrgIDKnowledgeNotesGetParams struct {
	After      *string `form:"after,omitempty" json:"after,omitempty"`
	First      *int    `form:"first,omitempty" json:"first,omitempty"`
	Search     *string `form:"search,omitempty" json:"search,omitempty"`
	FolderPath *string `form:"folder_path,omitempty" json:"folder_path,omitempty"`
	PinnedRepo *string `form:"pinned_repo,omitempty" json:"pinned_repo,omitempty"`
}

// HandleListPlaybooksV3OrganizationsOrgIDPlaybooksGetParams defines parameters for HandleListPlaybooksV3OrganizationsOrgIDPlaybooksGet.
type HandleListPlaybooksV3OrganizationsOrgIDPlaybooksGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleListSchedulesV3OrganizationsOrgIDSchedulesGetParams defines parameters for HandleListSchedulesV3OrganizationsOrgIDSchedulesGet.
type HandleListSchedulesV3OrganizationsOrgIDSchedulesGetParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// HandleListSecretsV3OrganizationsOrgIDSecretsGetParams defines parameters for HandleListSecretsV3OrganizationsOrgIDSecretsGet.
type HandleListSecretsV3OrganizationsOrgIDSecretsGetParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	First *int    `form:"first,omitempty" json:"first,omitempty"`
}

// HandleSetOrgDevinAcuLimitV3EnterpriseConsumptionAcuLimitsDevinOrganizationsOrgIDPutJSONRequestBody defines body for HandleSetOrgDevinAcuLimitV3EnterpriseConsumptionAcuLimitsDevinOrganizationsOrgIDPut for application/json ContentType.
type HandleSetOrgDevinAcuLimitV3EnterpriseConsumptionAcuLimitsDevinOrganizationsOrgIDPutJSONRequestBody = UpdateACULimitRequest

// HandleBulkRegisterAccountIdpGroupsV3EnterpriseIdpGroupsPostJSONRequestBody defines body for HandleBulkRegisterAccountIdpGroupsV3EnterpriseIdpGroupsPost for application/json ContentType.
type HandleBulkRegisterAccountIdpGroupsV3EnterpriseIdpGroupsPostJSONRequestBody = IdpGroupsBulkCreateRequest

// HandleAddIPAccessListV3EnterpriseIPAccessListPostJSONRequestBody defines body for HandleAddIPAccessListV3EnterpriseIPAccessListPost for application/json ContentType.
type HandleAddIPAccessListV3EnterpriseIPAccessListPostJSONRequestBody = IPAccessListAddRequest

// HandleReplaceIPAccessListV3EnterpriseIPAccessListPutJSONRequestBody defines body for HandleReplaceIPAccessListV3EnterpriseIPAccessListPut for application/json ContentType.
type HandleReplaceIPAccessListV3EnterpriseIPAccessListPutJSONRequestBody = IPAccessListReplaceRequest

// HandleCreateNoteV3EnterpriseKnowledgeNotesPostJSONRequestBody defines body for HandleCreateNoteV3EnterpriseKnowledgeNotesPost for application/json ContentType.
type HandleCreateNoteV3EnterpriseKnowledgeNotesPostJSONRequestBody = KnowledgeNoteCreateRequest

// HandleUpdateNoteV3EnterpriseKnowledgeNotesNoteIDPutJSONRequestBody defines body for HandleUpdateNoteV3EnterpriseKnowledgeNotesNoteIDPut for application/json ContentType.
type HandleUpdateNoteV3EnterpriseKnowledgeNotesNoteIDPutJSONRequestBody = KnowledgeNoteCreateRequest

// HandleUpdateEnterpriseIdpGroupRoleV3EnterpriseMembersIdpGroupsIdpGroupNamePatchJSONRequestBody defines body for HandleUpdateEnterpriseIdpGroupRoleV3EnterpriseMembersIdpGroupsIdpGroupNamePatch for application/json ContentType.
type HandleUpdateEnterpriseIdpGroupRoleV3EnterpriseMembersIdpGroupsIdpGroupNamePatchJSONRequestBody = IdpGroupUpdateRoleRequest

// HandleAssignEnterpriseIdpGroupRoleV3EnterpriseMembersIdpGroupsIdpGroupNamePostJSONRequestBody defines body for HandleAssignEnterpriseIdpGroupRoleV3EnterpriseMembersIdpGroupsIdpGroupNamePost for application/json ContentType.
type HandleAssignEnterpriseIdpGroupRoleV3EnterpriseMembersIdpGroupsIdpGroupNamePostJSONRequestBody = IdpGroupUpdateRoleRequest

// HandleUpdateEnterpriseServiceUserRoleV3EnterpriseMembersServiceUsersServiceUserIDPatchJSONRequestBody defines body for HandleUpdateEnterpriseServiceUserRoleV3EnterpriseMembersServiceUsersServiceUserIDPatch for application/json ContentType.
type HandleUpdateEnterpriseServiceUserRoleV3EnterpriseMembersServiceUsersServiceUserIDPatchJSONRequestBody = ServiceUserUpdateRoleRequest

// HandleAssignEnterpriseServiceUserRoleV3EnterpriseMembersServiceUsersServiceUserIDPostJSONRequestBody defines body for HandleAssignEnterpriseServiceUserRoleV3EnterpriseMembersServiceUsersServiceUserIDPost for application/json ContentType.
type HandleAssignEnterpriseServiceUserRoleV3EnterpriseMembersServiceUsersServiceUserIDPostJSONRequestBody = ServiceUserUpdateRoleRequest

// HandleBulkInviteEnterpriseUsersV3EnterpriseMembersUsersPostJSONRequestBody defines body for HandleBulkInviteEnterpriseUsersV3EnterpriseMembersUsersPost for application/json ContentType.
type HandleBulkInviteEnterpriseUsersV3EnterpriseMembersUsersPostJSONRequestBody = UserBulkCreateRequest

// HandleUpdateEnterpriseUserRoleV3EnterpriseMembersUsersUserIDPatchJSONRequestBody defines body for HandleUpdateEnterpriseUserRoleV3EnterpriseMembersUsersUserIDPatch for application/json ContentType.
type HandleUpdateEnterpriseUserRoleV3EnterpriseMembersUsersUserIDPatchJSONRequestBody = UserUpdateRoleRequest

// UpdateOrgGroupsConfigV3EnterpriseOrgGroupLimitsPutJSONRequestBody defines body for UpdateOrgGroupsConfigV3EnterpriseOrgGroupLimitsPut for application/json ContentType.
type UpdateOrgGroupsConfigV3EnterpriseOrgGroupLimitsPutJSONRequestBody = OrgGroupsConfig

// HandleCreateOrganizationV3EnterpriseOrganizationsPostJSONRequestBody defines body for HandleCreateOrganizationV3EnterpriseOrganizationsPost for application/json ContentType.
type HandleCreateOrganizationV3EnterpriseOrganizationsPostJSONRequestBody = OrganizationCreateRequest

// HandleUpdateOrganizationV3EnterpriseOrganizationsOrgIDPatchJSONRequestBody defines body for HandleUpdateOrganizationV3EnterpriseOrganizationsOrgIDPatch for application/json ContentType.
type HandleUpdateOrganizationV3EnterpriseOrganizationsOrgIDPatchJSONRequestBody = OrganizationUpdateRequest

// HandleBulkCreateOrganizationGitPermissionsV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsPostJSONRequestBody defines body for HandleBulkCreateOrganizationGitPermissionsV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsPost for application/json ContentType.
type HandleBulkCreateOrganizationGitPermissionsV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsPostJSONRequestBody = GitPermissionBulkCreateRequest

// HandleReplaceOrganizationGitPermissionsV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsPutJSONRequestBody defines body for HandleReplaceOrganizationGitPermissionsV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsPut for application/json ContentType.
type HandleReplaceOrganizationGitPermissionsV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsPutJSONRequestBody = GitPermissionBulkCreateRequest

// HandleUpdateOrganizationGitPermissionV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsGitPermissionIDPatchJSONRequestBody defines body for HandleUpdateOrganizationGitPermissionV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsGitPermissionIDPatch for application/json ContentType.
type HandleUpdateOrganizationGitPermissionV3EnterpriseOrganizationsOrgIDGitProvidersPermissionsGitPermissionIDPatchJSONRequestBody = GitPermissionUpdateRequest

// HandleUpdateOrganizationIdpGroupRoleV3EnterpriseOrganizationsOrgIDMembersIdpGroupsIdpGroupNamePatchJSONRequestBody defines body for HandleUpdateOrganizationIdpGroupRoleV3EnterpriseOrganizationsOrgIDMembersIdpGroupsIdpGroupNamePatch for application/json ContentType.
type HandleUpdateOrganizationIdpGroupRoleV3EnterpriseOrganizationsOrgIDMembersIdpGroupsIdpGroupNamePatchJSONRequestBody = IdpGroupUpdateRoleRequest

// HandleAssignOrganizationIdpGroupRoleV3EnterpriseOrganizationsOrgIDMembersIdpGroupsIdpGroupNamePostJSONRequestBody defines body for HandleAssignOrganizationIdpGroupRoleV3EnterpriseOrganizationsOrgIDMembersIdpGroupsIdpGroupNamePost for application/json ContentType.
type HandleAssignOrganizationIdpGroupRoleV3EnterpriseOrganizationsOrgIDMembersIdpGroupsIdpGroupNamePostJSONRequestBody = IdpGroupUpdateRoleRequest

// HandleUpdateOrganizationServiceUserRoleV3EnterpriseOrganizationsOrgIDMembersServiceUsersServiceUserIDPatchJSONRequestBody defines body for HandleUpdateOrganizationServiceUserRoleV3EnterpriseOrganizationsOrgIDMembersServiceUsersServiceUserIDPatch for application/json ContentType.
type HandleUpdateOrganizationServiceUserRoleV3EnterpriseOrganizationsOrgIDMembersServiceUsersServiceUserIDPatchJSONRequestBody = ServiceUserUpdateRoleRequest

// HandleAssignOrganizationServiceUserRoleV3EnterpriseOrganizationsOrgIDMembersServiceUsersServiceUserIDPostJSONRequestBody defines body for HandleAssignOrganizationServiceUserRoleV3EnterpriseOrganizationsOrgIDMembersServiceUsersServiceUserIDPost for application/json ContentType.
type HandleAssignOrganizationServiceUserRoleV3EnterpriseOrganizationsOrgIDMembersServiceUsersServiceUserIDPostJSONRequestBody = ServiceUserUpdateRoleRequest

// HandleUpdateOrganizationUserRoleV3EnterpriseOrganizationsOrgIDMembersUsersUserIDPatchJSONRequestBody defines body for HandleUpdateOrganizationUserRoleV3EnterpriseOrganizationsOrgIDMembersUsersUserIDPatch for application/json ContentType.
type HandleUpdateOrganizationUserRoleV3EnterpriseOrganizationsOrgIDMembersUsersUserIDPatchJSONRequestBody = UserUpdateRoleRequest

// HandleAssignOrganizationUserRoleV3EnterpriseOrganizationsOrgIDMembersUsersUserIDPostJSONRequestBody defines body for HandleAssignOrganizationUserRoleV3EnterpriseOrganizationsOrgIDMembersUsersUserIDPost for application/json ContentType.
type HandleAssignOrganizationUserRoleV3EnterpriseOrganizationsOrgIDMembersUsersUserIDPostJSONRequestBody = UserUpdateRoleRequest

// HandleAppendOrganizationAllowedTagsV3EnterpriseOrganizationsOrgIDTagsPostJSONRequestBody defines body for HandleAppendOrganizationAllowedTagsV3EnterpriseOrganizationsOrgIDTagsPost for application/json ContentType.
type HandleAppendOrganizationAllowedTagsV3EnterpriseOrganizationsOrgIDTagsPostJSONRequestBody = TagsCreateRequest

// HandleReplaceOrganizationAllowedTagsV3EnterpriseOrganizationsOrgIDTagsPutJSONRequestBody defines body for HandleReplaceOrganizationAllowedTagsV3EnterpriseOrganizationsOrgIDTagsPut for application/json ContentType.
type HandleReplaceOrganizationAllowedTagsV3EnterpriseOrganizationsOrgIDTagsPutJSONRequestBody = TagsCreateRequest

// SetOrganizationDefaultTagV3EnterpriseOrganizationsOrgIDTagsDefaultPutJSONRequestBody defines body for SetOrganizationDefaultTagV3EnterpriseOrganizationsOrgIDTagsDefaultPut for application/json ContentType.
type SetOrganizationDefaultTagV3EnterpriseOrganizationsOrgIDTagsDefaultPutJSONRequestBody = DefaultTagRequest

// HandleCreatePlaybookV3EnterprisePlaybooksPostJSONRequestBody defines body for HandleCreatePlaybookV3EnterprisePlaybooksPost for application/json ContentType.
type HandleCreatePlaybookV3EnterprisePlaybooksPostJSONRequestBody = PlaybookCreateRequest

// HandleUpdatePlaybookV3EnterprisePlaybooksPlaybookIDPutJSONRequestBody defines body for HandleUpdatePlaybookV3EnterprisePlaybooksPlaybookIDPut for application/json ContentType.
type HandleUpdatePlaybookV3EnterprisePlaybooksPlaybookIDPutJSONRequestBody = PlaybookCreateRequest

// HandleCreateNoteV3OrganizationsOrgIDKnowledgeNotesPostJSONRequestBody defines body for HandleCreateNoteV3OrganizationsOrgIDKnowledgeNotesPost for application/json ContentType.
type HandleCreateNoteV3OrganizationsOrgIDKnowledgeNotesPostJSONRequestBody = KnowledgeNoteCreateRequest

// HandleUpdateNoteV3OrganizationsOrgIDKnowledgeNotesNoteIDPutJSONRequestBody defines body for HandleUpdateNoteV3OrganizationsOrgIDKnowledgeNotesNoteIDPut for application/json ContentType.
type HandleUpdateNoteV3OrganizationsOrgIDKnowledgeNotesNoteIDPutJSONRequestBody = KnowledgeNoteCreateRequest

// HandleCreatePlaybookV3OrganizationsOrgIDPlaybooksPostJSONRequestBody defines body for HandleCreatePlaybookV3OrganizationsOrgIDPlaybooksPost for application/json ContentType.
type HandleCreatePlaybookV3OrganizationsOrgIDPlaybooksPostJSONRequestBody = PlaybookCreateRequest

// HandleUpdatePlaybookV3OrganizationsOrgIDPlaybooksPlaybookIDPutJSONRequestBody defines body for HandleUpdatePlaybookV3OrganizationsOrgIDPlaybooksPlaybookIDPut for application/json ContentType.
type HandleUpdatePlaybookV3OrganizationsOrgIDPlaybooksPlaybookIDPutJSONRequestBody = PlaybookCreateRequest

// HandleCreateScheduleV3OrganizationsOrgIDSchedulesPostJSONRequestBody defines body for HandleCreateScheduleV3OrganizationsOrgIDSchedulesPost for application/json ContentType.
type HandleCreateScheduleV3OrganizationsOrgIDSchedulesPostJSONRequestBody = ScheduleCreateRequest

// HandleUpdateScheduleV3OrganizationsOrgIDSchedulesScheduleIDPatchJSONRequestBody defines body for HandleUpdateScheduleV3OrganizationsOrgIDSchedulesScheduleIDPatch for application/json ContentType.
type HandleUpdateScheduleV3OrganizationsOrgIDSchedulesScheduleIDPatchJSONRequestBody = ScheduleUpdateRequest

// HandleCreateSecretV3OrganizationsOrgIDSecretsPostJSONRequestBody defines body for HandleCreateSecretV3OrganizationsOrgIDSecretsPost for application/json ContentType.
type HandleCreateSecretV3OrganizationsOrgIDSecretsPostJSONRequestBody = SecretCreateRequest
